### ISSUE TITLE
firefox doesnt works (latest version)

### ISSUE THREAD

**Issue by arxdeus** [SaulBerrenson/BrowserStealer#3]
Hello, chromium parser works fine, but firefox - not, it throws continue and can't initialize decryptor
Here's screenshot where's it stops works

![image](https://user-images.githubusercontent.com/39557395/125159334-6bc37580-e17f-11eb-9a00-2056d269e5f7.png)

**Comment by SaulBerrenson** [comment]
Hi, thank you for your question. I think - you used x64 build when dynamic libs (mozglue.dll and nss3.dll are x64 or vice versa). You can see on this screenshot what my build and build these libs is same and it was loaded success - [proof](https://i.imgur.com/6g1WAXr.png) Try check these libs for type of build using software "detect it easy". And if you have firefox with x64 libs - build project with same type and vice versa. After these actions, please give me feedback. Have a nice day!)

**Comment by MindMayhem** [comment]
Nothing changed, but i noticed parent problem for this problem - app can't find any mozilla browsers, it just returns empty List
I have installed latest Mozilla Firefox, which located at default path - C:\Program Files\Mozilla Firefox
We trying to search mozglue.dll and other libs not in the main location of browsers
![image](https://user-images.githubusercontent.com/39557395/125170868-c7aaf000-e1b9-11eb-8304-28bd33317a2b.png)

**Comment by MindMayhem** [comment]
And here's dat boi
![image](https://user-images.githubusercontent.com/39557395/125170976-67687e00-e1ba-11eb-84c2-5da769f368dd.png)

**Comment by arxdeus** [comment]
Okay, mate, i finally found source of this problem
**_regedit_helper::get_subkeys_** return 0 from **_SOFTWARE\Clients\StartMenuInternet_**

As you see at picture, I have Firefox directory here, but regedit_helper ignore it, idk why, because logically everything fine

![image](https://user-images.githubusercontent.com/39557395/125175920-1ebfbd80-e1d8-11eb-8738-cd3a5fc6a082.png)


Any ideas for solution?

**Comment by SaulBerrenson** [comment]
> 
> 
> Okay, mate, i finally found source of this problem
> **_regedit_helper::get_subkeys_** return 0 from **_SOFTWARE\Clients\StartMenuInternet_**
> 
> As you see at picture, I have Firefox directory here, but regedit_helper ignore it, idk why, because logically everything fine
> 
> ![image](https://user-images.githubusercontent.com/39557395/125175920-1ebfbd80-e1d8-11eb-8738-cd3a5fc6a082.png)
> 
> Any ideas for solution?

Probably, this method search of gecko browsers requires admin rights. Try load IDE from with admin rights and go to these breakpoints what you shown.

**Comment by MindMayhem** [comment]
I tried both variants with admin permissions, but nothing changed
Main problem in Regedit, seems like it can't read adequately subkeys in registry.

![image](https://user-images.githubusercontent.com/39557395/125204430-fee6d300-e285-11eb-8720-a7806a968d06.png)

**Comment by SaulBerrenson** [comment]
> 
> 
> I tried both variants with admin permissions, but nothing changed
> Main problem in Regedit, seems like it can't read adequately subkeys in registry.
> 
> ![image](https://user-images.githubusercontent.com/39557395/125204430-fee6d300-e285-11eb-8720-a7806a968d06.png)

okay, i know one way yet for looking specific folder app for gekko. So, wait update.

**Comment by SaulBerrenson** [comment]
> 
> 
> I tried both variants with admin permissions, but nothing changed
> Main problem in Regedit, seems like it can't read adequately subkeys in registry.
> 
> ![image](https://user-images.githubusercontent.com/39557395/125204430-fee6d300-e285-11eb-8720-a7806a968d06.png)

Update to lastest version from main branch. The way to searching program folder was changed.

**Comment by MindMayhem** [comment]
It doesn't work anyway

![image](https://user-images.githubusercontent.com/39557395/125211778-74b46400-e2b1-11eb-90e1-13f5405b4d0e.png)

**Comment by MindMayhem** [comment]
But I noticed one interest thing, i edited my **_get_mozilla_program_dir_** func like this
```
String firefox_parser::get_mozilla_program_dir(String dirProfile)
{
	std::string progDir;
	std::ifstream file(dirProfile+"\\compatibility.ini");
	if (file.is_open()) {
		std::string line;
		while (std::getline(file, line)) {
			if (line.find("LastPlatformDir=") != std::string::npos) {
				std::string::size_type i = line.find("LastPlatformDir=");
				std::string erasee = "LastPlatformDir=";
				if (i != std::string::npos) {
					line.erase(i, erasee.length());
					progDir = line;

				}
			}

		}
		file.close();
	}
	return progDir;
}
```

And it return correct way to program dir (_C:/Program Files/Mozilla Firefox/_)
**BUT** FirefoxDecryptor throw error like this: 
```
Exception thrown: write access violation.
out.data was 0x1110637323C13BE. 

```
(translated with Google Translate)
![image](https://user-images.githubusercontent.com/39557395/125211944-bb568e00-e2b2-11eb-959f-1bd52c017f17.png)

**Comment by MindMayhem** [comment]
Removed this part of the code and the output almost satisfies me, but strange signatures stays at end of credentials
We can't trim this signatures because they are generates with random length and content (every launch return new signature)


![image](https://user-images.githubusercontent.com/39557395/125212298-15f0e980-e2b5-11eb-9623-1e2632dd4933.png)

**Comment by arxdeus** [comment]
Please write in README what it should be compiled with **Cmake**, not integrated Visual studio compiler
Everything works, thanks

**Comment by SaulBerrenson** [comment]
okay, i'll update it
